### ISSUE TITLE
prototxt example

### ISSUE THREAD

**Issue by hustzeyu** [blankWorld/GroupNorm-caffe#1]
Hi, thank you for sharing. Is it possible to give us a prototxt file to show where to add this layer and how does it work? Please, thank you!

**Comment by blankWorld** [comment]
Thank you for your interest in my work.
GN prototxt just like BN.
layer {
  name: "conv1_gn"
  type: "GroupNorm"
  bottom: "conv1"
  top: "conv1"
    group_norm_param {
	    eps: 1e-5
	    group_num: 32
    }
}

**Comment by hustzeyu** [comment]
Thank you!

**Comment by hungsing92** [comment]
Hi. Does it need Scale Layer ?

**Comment by CQUCL** [comment]
I also want to know if it need Scale Layer? Do you have experiments about this?

**Comment by rmxhhh** [comment]
Hi,Iwant to know what is the group_num,Can I remove this parameter? Is the parameter "eps=1e-5" universal or do I need to change its value? It is very important for me.Thank you. @blankWorld

**Comment by lengly** [comment]
@hungsing92 @CQUCL group norm also need scale layer, just like batch norm.
@rmxhhh  It's how many groups you divide channel. For detail you can see the paper.
