### ISSUE TITLE
 "caffe_gpu_sqrt" is undefined

### ISSUE THREAD

**Issue by ngunauj** [blankWorld/GroupNorm-caffe#3]
how to solve this problem `src/caffe/layers/group_norm_layer.cu(37): error: identifier "caffe_gpu_sqrt" is undefined`

**Comment by CQUCL** [comment]
> how to solve this problem `src/caffe/layers/group_norm_layer.cu(37): error: identifier "caffe_gpu_sqrt" is undefined`

I also have this problem.Have you solved it?

**Comment by ngunauj** [comment]
it's the version problem of your caffe. if you don't want to update your caffe, you can add 'caffe_gpu_sqrt' method  like [math_functions.cu](https://github.com/BVLC/caffe/blob/master/src/caffe/util/math_functions.cu)

**Comment by CQUCL** [comment]
> it's the version problem of your caffe. if you don't want to update your caffe, you can add 'caffe_gpu_sqrt' method like [math_functions.cu](https://github.com/BVLC/caffe/blob/master/src/caffe/util/math_functions.cu)

thanks, can you give me your qq?　Maybe I can ask for your help
